In [53]:
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv('https://raw.githubusercontent.com/Rajvardhan180/House_Price_Prediction/main/data/Housing.csv')
data.columns = data.columns.str.strip().str.lower()
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [54]:
premium_data = data[
    (data['guestroom'] == 'yes') & 
    (data['airconditioning'] == 'yes') & 
    (data['area'] > 3000)
]

In [55]:
avg_price = premium_data.groupby('furnishingstatus')['price'].mean()
avg_bedrooms = premium_data.groupby('furnishingstatus')['bedrooms'].mean()
property_count = premium_data.groupby('furnishingstatus')['price'].count()

In [56]:
result = pd.DataFrame({
    'avg_price' : avg_price,
    'avg_bedrooms': avg_bedrooms,
    'property_count': property_count
})
result

                     avg_price  avg_bedrooms  property_count
furnishingstatus
furnished         7.039455e+06      3.545455              22
semi-furnished    6.170231e+06      3.000000              13
unfurnished       7.185938e+06      3.125000               8

In [57]:
data['energyload'] = (data['area']*0.5) + (data['bedrooms']*100) +  (data['bathrooms'] * 150)

In [58]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,energyload
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,4410.0
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,5480.0
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,5580.0
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,4450.0
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,4260.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,1850.0
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,1650.0
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,2160.0
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished,1905.0
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,2375.0

In [59]:
filtereddf =  data[(data['hotwaterheating'] == 'yes') & (data['airconditioning'] == 'yes')]

In [60]:
filtereddf

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,energyload
378,3640000,2275,3,1,3,yes,no,no,yes,yes,0,yes,semi-furnished,1587.5

In [61]:
avg_energyload = filtereddf.groupby('furnishingstatus')['energyload'].mean()
avg_price2 = filtereddf.groupby('furnishingstatus')['price'].mean()

In [62]:
result2 =  pd.DataFrame({
    'avg_energyload' : avg_energyload,
    'avg_price2': avg_price2,
})
result2

                  avg_energyload  avg_price2
furnishingstatus
semi-furnished            1587.5   3640000.0